stacks:
- content-api-sanity-tests
regions:
- eu-west-1
deployments:
  sanity-tests:
    type: autoscaling
    parameters:
      bucketSsmLookup: true
    dependencies: [sanity-tests-ami-update]
  sanity-tests-ami-update:
    type: ami-cloudformation-parameter
    app: sanity-tests
    parameters:
      amiTags:
        Recipe: ubuntu-bionic-capi
        AmigoStage: PROD
      amiEncrypted: true
