name: Build and upload

on: [push]

jobs:
  sanity-tests:
    runs-on: ubuntu-latest

    # The first two permissions are needed to interact with GitHub's OIDC Token endpoint.
    # The second set of three permissions are needed to write test results back to GH
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: cdk/yarn.lock

      - run: yarn install --frozen-lockfile
        name: Prepare for CDK infrastructure build
        working-directory: cdk
      - run: yarn test
        name: Test CDK infrastructure integrity
        working-directory: cdk
      - run: yarn synth
        name: Build infrastructure definition from CDK
        working-directory: cdk

      - uses: guardian/setup-scala@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          role-session-name: content-api-sanity-tests-build

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: |
          sbt debian:packageBin

      - uses: guardian/actions-riff-raff@v2
        with:
          configPath: riff-raff.yaml
          projectName: Content Platforms::content-api-sanity-tests
          buildNumberOffset: 453
          contentDirectories: |
            cloudformation:
              - cdk/cdk.out/SanityTests-CODE.template.json
              - cdk/cdk.out/SanityTests-PROD.template.json
            sanity-tests:
              - target/sanity-tests_1.0_all.deb

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml
